/*
 * Proyecto ProyectoCalculadora - Archivo CalculadoraBasica2.java - Compañia DAW
 * Licencia Creative Commons BY-NC-SA 4.0
 * https://creativecommons.org/licenses/by-nc-sa/4.0/
 */

/**
 *
 * @author Cristina Carrascosa <cctausias@gmail.com>
 */
public class CalculadoraBasica2 extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraBasica2
     */
    public CalculadoraBasica2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        num1 = new javax.swing.JLabel();
        num2 = new javax.swing.JLabel();
        innum1 = new javax.swing.JTextField();
        innum2 = new javax.swing.JTextField();
        botSumar = new javax.swing.JButton();
        botRestar = new javax.swing.JButton();
        botMult = new javax.swing.JButton();
        botDiv = new javax.swing.JButton();
        reSum = new javax.swing.JLabel();
        reRes = new javax.swing.JLabel();
        resMult = new javax.swing.JLabel();
        reDiv = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Basica 2");

        num1.setText("Número 1");

        num2.setText("Número 2");

        botSumar.setText("Sumar");
        botSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSumarActionPerformed(evt);
            }
        });

        botRestar.setText("Restar");
        botRestar.setActionCommand("");
        botRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botRestarActionPerformed(evt);
            }
        });

        botMult.setText("Mult...");
        botMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botMultActionPerformed(evt);
            }
        });

        botDiv.setText("Dividir");
        botDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botDivActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(num1)
                        .addGap(18, 18, 18)
                        .addComponent(innum1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(num2)
                        .addGap(18, 18, 18)
                        .addComponent(innum2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botSumar)
                    .addComponent(botMult)
                    .addComponent(botRestar)
                    .addComponent(botDiv))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reSum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reRes)
                    .addComponent(resMult)
                    .addComponent(reDiv))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {innum1, innum2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botDiv, botMult, botRestar, botSumar});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {reDiv, reRes, reSum, resMult});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(num1)
                        .addComponent(innum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botSumar))
                    .addComponent(reSum, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num2)
                    .addComponent(innum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botRestar)
                    .addComponent(reRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botMult)
                    .addComponent(resMult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reDiv)
                    .addComponent(botDiv))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botDiv, botMult, botRestar, botSumar, reDiv, reRes, reSum, resMult});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botRestarActionPerformed
        // Variables
        String n1 = innum1.getText();
        String n2 = innum2.getText();
        
        // Convertir las varibles a numeros
        double d1 = Double.parseDouble(n1);
        double d2 = Double.parseDouble(n2);
        
        // Calcular
        double res = d1 - d2;
        
        // Mostrar
        reRes.setText(""+n2);
    }//GEN-LAST:event_botRestarActionPerformed

    private void botSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSumarActionPerformed
        // Convertir los textos de JTexEdit en números.
        String n1 = innum1.getText();
        String n2 = innum2.getText();
        
        double d1 = Double.parseDouble(n1);
        double d2 = Double.parseDouble(n2);
        
        // Realizar la suma
        double res = d1 + d2;
        
        // Mostrar resultado
        reSum.setText(""+ res);
        
    }//GEN-LAST:event_botSumarActionPerformed

    private void botMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botMultActionPerformed
        String n1 = innum1.getText();
        String n2 = innum2.getText();
        
        double d1 = Double.parseDouble(n1);
        double d2 = Double.parseDouble(n2);
        
        double res = d1 * d2;
        
        resMult.setText(""+res);
    }//GEN-LAST:event_botMultActionPerformed

    private void botDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botDivActionPerformed
        String n1 = innum1.getText();
        String n2 = innum2.getText();
        
        double d1= Double.parseDouble(n1);
        double d2= Double.parseDouble(n2);
        
        double res = d1/d2;
        
        if (d2 == 0){
            reDiv.setText("Error");
        }else {
            reDiv.setText(""+res);
        }
    }//GEN-LAST:event_botDivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBasica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBasica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBasica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBasica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraBasica2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botDiv;
    private javax.swing.JButton botMult;
    private javax.swing.JButton botRestar;
    private javax.swing.JButton botSumar;
    private javax.swing.JTextField innum1;
    private javax.swing.JTextField innum2;
    private javax.swing.JLabel num1;
    private javax.swing.JLabel num2;
    private javax.swing.JLabel reDiv;
    private javax.swing.JLabel reRes;
    private javax.swing.JLabel reSum;
    private javax.swing.JLabel resMult;
    // End of variables declaration//GEN-END:variables
}
